---
- name: Download NiFi Registry binary
  get_url:
    url: "{{ download_mirror_uri }}/nifi/{{ nifi_registry_version }}/nifi-registry-{{ nifi_registry_version }}-bin.zip"
    dest: "/tmp/nifi-registry-{{ nifi_registry_version }}-bin.zip"

- name: Unpack NiFi Registry binary
  unarchive:
    remote_src: "yes"
    src: "/tmp/nifi-registry-{{ nifi_registry_version }}-bin.zip"
    dest: "{{ nifi_registry_config_dirs.install }}/"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    creates: "{{ nifi_registry_config_dirs.install }}/nifi-registry-{{ nifi_registry_version }}"

- name: Fix permissions
  file:
    path: "{{ nifi_registry_config_dirs.install }}/nifi-registry-{{ nifi_registry_version }}"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    recurse: "yes"

- name: Create NiFi Registry symlink
  file:
    src: "nifi-registry-{{ nifi_registry_version }}"
    path: "{{ nifi_registry_config_dirs.home }}"
    state: "link"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Create directories
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
  with_items:
    - "{{ nifi_registry_config_dirs.run }}"
    - "{{ nifi_registry_config_dirs.logs }}"

- name: Set NiFi Registry home
  copy:
    dest: "/etc/profile.d/nifi-registry-home.sh"
    content: "export NIFI_REGISTRY_HOME={{ nifi_registry_config_dirs.home }}"
